### ISSUE TITLE
Issue with import configurations

### ISSUE THREAD

**Issue by jamesrweb** [stryker-mutator/stryker-js#2890] opened 2021-05-10 14:27 UTC
**Summary**

Stryker errors out and say it cannot support import statements since the file is not a module but our default testing setup and configs work fine. Files are found correctly for the run and the temp files generate fine so it seems weird that I get the following error:

> SyntaxError: Cannot use import statement outside a module

It is strange because I have pointed stryker to our working configs so this should just work IMO but do tell me if I am missing something!

One other thing to note is that the jest config ignores the `stryker-tmp` directory but it tried to run tests in there for some reason too.

**Stryker config**

```js
const { join } = require("path")

/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  tempDirName: "stryker-tmp",
  packageManager: "yarn",
  commandRunner: {
    command: "npx yarn run test:client",
  },
  reporters: ["html", "clear-text", "progress"],
  testRunner: "jest",
  jest: {
    configFile: join(__dirname, "client", "jest.config.js"),
  },
  coverageAnalysis: "perTest",
  checkers: ["typescript"],
  tsconfigFile: join(__dirname, "client", "tsconfig.test.json"),
  mutate: ["client/components/modules/checkout/*.ts?(x)"],
}
```

**Test runner config**

This is the `client/jest.config.js`:

```js
const { pathsToModuleNameMapper } = require("ts-jest/utils")
const tsConfig = require("./tsconfig.json")

const aliases = tsConfig.compilerOptions.paths || {}
const project = "client"
const prefix = "<rootDir>/../"

module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  testMatch: [prefix + project + "/**/*.test.ts"],
  globals: {
    "ts-jest": {
      tsconfig: project + "/tsconfig.test.json",
    },
  },
  testPathIgnorePatterns: ["/stryker-tmp/"],
  moduleNameMapper: pathsToModuleNameMapper(aliases, { prefix }),
  modulePaths: ["node_modules", "<rootDir>"],
  watchPathIgnorePatterns: ["__file_snapshots__"],
}
```

This is the `client/jtsconfig.test.json`:

```json
{
  "$schema": "http://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "jsx": "react",
    "types": ["jest", "node"]
  },
  "exclude": [],
  "extends": "./tsconfig.json"
}
```

This is the `client/tsconfig.json`:

```json
{
  "$schema": "http://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "..",
    "downlevelIteration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "module": "ESNext",
    "moduleResolution": "Node",
    "noEmit": true,
    "paths": {}, // omitted deliberately for the issue
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "ES5",
    "types": ["grecaptcha"]
  },
  "exclude": ["node_modules", "**/*.test.ts"],
  "include": ["**/*"]
}
```

**Stryker environment**

```git
@stryker-mutator/core@4.6.0,
@stryker-mutator/jest-runner@4.6.0,
@stryker-mutator/typescript-checker@4.6.0
jest@26.1.0
ts-jest@26.5.6
typescript@4.2.4
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 14.15.5
| npm              | 6.14.12
| Operating System | MacOS Big Sur

**Add stryker.log**

The error itself logs as:

```text
16:19:28 (34863) ERROR DryRunExecutor One or more tests resulted in an error:
	undefinedCannot use import statement outside a module Jest encountered an unexpected token

This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

Here's what you can do:
 • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
 • If you need a custom transformation specify a "transform" option in your config.
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/en/configuration.html

Details:

file_path_omitted:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { checkout, clearStorage, expectPathIs, pages, productDetailPage, setFeatures, setViewport, timeouts } from "../../abstraction";
```

**Comment by nicojs** [comment] 2021-05-10 14:53
Hi James 👋, thanks for opening this issue.

Is it correct to note that your tests live _outside_ of your current working directory when running Stryker? Since it seems to be concatenated as `"<rootDir>/../client/**/*.test.ts""`?

Could you try to run Stryker with `--inPlace` mode, just to be sure? Using this setting will allow Stryker to mutate in place. It should eliminate any issues that have to do with file paths, temp dirs, etc. It will put your files back in place after it is done, so don't worry 😅.

There might also be an issue with disabling of type checking. `ts-jest` does type checking for you, Stryker needs to explicitly disables it. The way it does that is by writing `// @ts-nocheck` in all your project files. It tries to guess using `"{test,src,lib}/**/*.{js,ts,jsx,tsx,html,vue}"` by default. Your code seems to live in `client`, so please try  `"{test,src,lib,client}/**/*.{js,ts,jsx,tsx,html,vue}"`. See https://stryker-mutator.io/docs/stryker-js/configuration/#disabletypechecks-false--string

**Comment by nicojs** [comment] 2021-05-11 09:07
Hmm ok, but I'm still not ready to give up on my hypophysis about the `rootDir` causing issues

Could you try this for me: create a `jest.config.js` file in the directory where you run StrykerJS from, and from that jest config, re-export the config from the jest.config.js you already have. For example:

```js
module.exports = require('./client/jest.config');
```

Next, try to run `jest` with it. I'm almost convinced that you can reproduce the jest error this way.

> With our current setup, that change stops our CI finding the tests

Yeah, this is a bug in Stryker. We should support an alternative root dir.

**Comment by jamesrweb** [comment] 2021-05-21 14:49
@nicojs you could be onto something, seems potentially like it could be the issue although by moving things it caused other issues on my end. Going with that assumption though, will this be something in Stryker 5 or is this not something that can be anticipated anytime soon to try it out "for real"?

**Comment by nicojs** [comment] 2021-06-04 16:43
> Going with that assumption though, will this be something in Stryker 5 or is this not something that can be anticipated anytime soon to try it out "for real"?

Well, I want to add support for jest's `rootDir`  in Stryker, but I'm not sure that would solve it for you. I'll try to add it soon.

**Comment by jamesrweb** [comment] 2021-06-05 18:00
@nicojs worth implementing and testing and we can go from there if not. Keep me posted please 🙏

**Comment by nicojs** [comment] 2021-06-14 16:00
Hi @jamesrweb we've just [5.1.0](https://github.com/stryker-mutator/stryker-js/releases/tag/v5.1.0) with a bunch of fixed issues for the jest-runner, including setting the `rootDir` correctly. Could you please try that one? It should work 🤞

**Comment by jamesrweb** [comment] 2021-07-12 16:05
@nicojs I just got around to this now and upgraded all local packages, removed node modules, ran the installer and then ran the `npx stryker run` command but now it throws this error when it is generating something internal, have you seen this before?

<img width="1791" alt="Bildschirmfoto 2021-07-12 um 18 01 18" src="https://user-images.githubusercontent.com/47126579/125319874-74f94180-e33b-11eb-85ab-5d473057166c.png">

**Comment by nicojs** [comment] 2021-07-13 11:29
Hmm interesting. I'm pretty sure this is the issue: https://github.com/stryker-mutator/mutation-testing-elements/issues/1254. Will fix asap

**Comment by nicojs** [comment] 2021-07-13 15:50
Fixed in 5.2.2, please try again 😇

**Comment by jamesrweb** [comment] 2021-07-14 10:10
@nicojs that's resolved that issue 👍🏻. Need to fix some errors about UMD globals before I can _really_ run the tests again, will write back here when I see the results or another error!

**Comment by jamesrweb** [comment] 2021-09-18 02:45
Issue seems to be resolved @nicojs 🎉

**Closed** 2021-10-08 17:07 UTC
Labels: 🐛 Bug
